services:
  - type: web
    name: spotify-reviews-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: spotify_reviews
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: LLM_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
